# Generated by Django 5.0.7 on 2024-08-03 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_log',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
